name: Psalm Analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - staging
      - dev-master

jobs:
  psalm:
    name: Psalm Static Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          version: 8.1
          extensions: psalm, phpunit
      - name: Psalm
        uses: docker://vimeo/psalm-github-actions
        with:
          security_analysis: true
          report_file: results.sarif
      - name: Upload Security Analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
